[package]
name = "gxbuild"
version = "1.0.1"
edition = "2021"

[lib]
name = "libgxbuild"
crate-type = ["rlib", "cdylib"]

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
libloading = { version = "0.8.6", optional = true }
thiserror = "1.0"
anyhow = "1.0"
crc32fast = "1.4"
rustyline = { version = "14.0.0", optional = true }
zerocopy = { version = "0.8.3", features = ["derive"] }
clap = { version = "4.6.0", features = ["derive"], optional = true }
byteorder = "1.5.0"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
rhai = "1.19.0"
shlex = "1.3.0"

[features]
default = ["cli", "ffi", "tui"]
cli = ["dep:clap"]
ffi = ["dep:libloading"]
tui = ["dep:rustyline"]
pygg = []

[build-dependencies]
cc = "1.0"
